### PR TITLE
Strip phpMyAdmin versions of their Ubuntu and Debian suffixes

### LINKED ISSUE #141: Too long phpmyadmin version
```
2017-05-09 08:15:42 Error: [PDOException] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'pma_version' at row 1 in /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php on line 39
Request URL: /incidents/create
Client IP: 37.221.176.78
Stack Trace:
#0 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Database/Connection.php(313): Cake\Database\Statement\MysqlStatement->execute()
#2 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Database/Query.php(213): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#3 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/ORM/Table.php(1916): Cake\Database\Query->execute()
#4 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/ORM/Table.php(1810): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#5 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/ORM/Table.php(1723): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#6 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/ORM/Table.php(1446): Cake\ORM\Table->Cake\ORM\{closure}()
#7 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Database/Connection.php(680): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#8 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/ORM/Table.php(1447): Cake\Database\Connection->transactional(Object(Closure))
#9 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/ORM/Table.php(1724): Cake\ORM\Table->_executeTransaction(Object(Closure), true)
#10 /home/reports/error-reporting-server/src/Model/Table/IncidentsTable.php(187): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 /home/reports/error-reporting-server/src/Controller/IncidentsController.php(34): App\Model\Table\IncidentsTable->createIncidentFromBugReport(Array)
#12 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Controller/Controller.php(440): App\Controller\IncidentsController->create()
#13 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#14 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\IncidentsController))
#15 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(60): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /home/reports/error-reporting-server/webroot/index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 {main}
```

### PR DESCRIPTION
**Pull request by devenbansod**
Fix #141

Signed-off-by: Deven Bansod <devenbansod.bits@gmail.com>

### CODE REVIEW

File: src/Model/Table/IncidentsTable.php [hunk 1]
```diff
@@ -438,6 +442,30 @@ protected function _getSimpleVersion($versionString, $versionLength)
...
+
+        // Check if $versionString matches the regexp
+        // and store the matched strings
+        if (preg_match($allowedRegexp, $versionString, $matches)) {
+            return $matches[0];
+        }
+
+        // If $versionString does not match the regexp at all,
+        // leave it as it is
+        return $versionString;
```
Comment (nijel) [inline src/Model/Table/IncidentsTable.php]: I'd prefer to have the sanitization code just once, used both in validation of saved incidents and migration.

**Comment by nijel** [comment]
I've added tests to your PR in https://github.com/devenbansod/error-reporting-server/pull/1.

File: config/Migrations/20170515135017_fix_long_pma_versions.php [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+        // Once applied, this migration can't be reversed
+        // but the migration itself is idempotent
+    }
+
+    private function _sanitizeVersionsInTable($table)
+    {
+        $rows = $this->fetchAll(
+            'SELECT `id`, `pma_version` FROM `' . $table . '`',
+            PDO::FETCH_ASSOC
+        );
```
Comment (nijel) [inline config/Migrations/20170515135017_fix_long_pma_versions.php]: This does load all the content into memory, right? I don't think it's reasonable to do with almost 2M records we have on the production system...

Comment (devenbansod) [inline config/Migrations/20170515135017_fix_long_pma_versions.php]: Yeah. It makes sense to use `fetch` to iterate instead of doing `fetchAll` at the one go. I will change the code accordingly today evening.

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by nijel** [comment]
JFYI the migration took about 22 minutes:

```
 == 20170515135017 FixLongPmaVersions: migrating
 == 20170515135017 FixLongPmaVersions: migrated 1316.9620s
```
