### PR TITLE
Fix ambiguous message on running Clean Old Notifications shell

### LINKED ISSUE #139: Failure on cleaning old notifications
This happens for last week or so on the production:

```

Welcome to CakePHP v3.4.6 Console
---------------------------------------------------------------
App : src
Path: /home/reports/error-reporting-server/src/
PHP : 7.0.16-3
---------------------------------------------------------------
2017-05-09 08:11:58 Error: FAILED: Deleting older Notifications!!
```

I've tried to run the generated SQL query manually and it works just fine...

### PR DESCRIPTION
**Pull request by devenbansod**
Fix #139

* Previously it sets failure message to display even when there is no failure but no rows were actually deleted

Signed-off-by: Deven Bansod <devenbansod.bits@gmail.com>

### CODE REVIEW

**Comment by nijel** [comment]
Merged, thanks for your contribution!

File: src/Shell/CleanOldNotifsShell.php [hunk 1]
```diff
@@ -37,10 +37,26 @@ public function main()
     {
         $XTime = time() - 60 * 24 * 3600;
         $conditions = array('Notifications.created <' => date('Y-m-d H:i:s', $XTime));
-        if (!$this->Notifications->deleteAll($conditions)) {
+
+        if ($this->Notifications->find('all', array('conditions' => $conditions))->count() === 0) {
+            // Check if there are any notifications to delete
+            Log::write(
+                'warning',
```
Comment (nijel) [inline src/Shell/CleanOldNotifsShell.php]: I've changed this to info - warning goes to stderr and that should indicate problem, but there is really none here...
